### PR TITLE
Miscellaneous header bar fixes

### PR DESCRIPTION
**Pull request by bendobos**
I fixed a couple of things that were not so nice about the header bar.

Most importantly, I changed the mobile breakpoint from 768px to 1000px, which opens up the mobile site much earlier. We will have to think about if this isn't too early but it saved some work making the search field scale when the room gets too tight to fit it.

### CODE REVIEW

**Comment by davidpdrsn** [comment]
👍 

I'll review this during the weekend.

**Comment by bendobos** [comment]
You don't really have to I think. Those were just some small CSS-fixes. I don't think it could break much.

**Comment by davidpdrsn** [comment]
Alright so no tests break?

Hopefully I'll get https://github.com/davidpdrsn/CardistryIO/issues/112 fixed this weekend.

**Comment by davidpdrsn** [comment]
@bendobos 

fullscreen_16_06_16_18_01

The username looks a bit misplaced in Safari. Looks fine in Chrome.

screen shot 2016-06-16 at 18 02 45

**Comment by bendobos** [comment]
That sucks. I will look into it.

**Comment by bendobos** [comment]
I fixed the issue with the profile button and all tests seem to pass. 
Are we good to merge now?

**Comment by davidpdrsn** [comment]
Yes. Merge at will.

**Pull request merged**
