### PR TITLE
Interface

### PR DESCRIPTION
**Pull request by bendobos**
I finished up the layout and styled the most important UI-elements. Made some stuff functional, like notifications.

Next, I'd like to start working on the individual screens (and do some fine-tuning to the layout here and there).

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Awesome, I'll look at getting it merged

**Comment by davidpdrsn** [comment]
I just got the thing merged and finished updating the tests. All is good :)

I'm really impressed with what you've done, I think it looks really great.

I have a few minor comments. These things we need to sorted out in the beginning so our work is more in sync :smile:

## Comments

I'd say avoid comments at all cost. We should aim at our code being easy to understand without needing comments. Comments will quickly go out of sync and thus cause more harm than good. I noticed this with the method called `cp` that you added. I renamed that to `current_path_class` and removed the comment. I also made some refactorings to the code to make it read a little nicer. What do you think about this?

Another type of comment are code thats commented out because we didn't wanna remove it because maybe we'll need it one day (or so we think). I tend to be ruthless with stuff like that and just get rid of it. Git has my back if I ever wanna get stuff back.

## Indentation

The standard indentation style for Ruby is 2 spaces, no tabs. I say we go with that for all code including haml, sass, and js.

## Double quotes

Very subjective but I say we go with double quotes instead of single quotes.

## Changes I made

Changed sign in/up buttons to links. They look the same, but tests are easier to write when they're normal links.

Added links to view your moves, required for tests. We can remove these when we have links somewhere else to view just your own moves. But for now the tests need these extra links.

Fixed bug in `current_path_class`, previously `cp`. It was only checking if the controller matched, not the action. So going to "/moves" and "/moves/all" would highlight the same links.

**Comment by bendobos** [comment]
I am so glad you like it! 

About comments:
I completely agree with you there. I actually googled the cp class and just copied it to test it out. As it worked perfectly right off the bar, I didn't even touch it again.
The commented out code fragments were actually a reference for me, as HAML is still new for me and I kept that to have a reference for syntax and routes. Forgot to remove them before sending the pull reqeust.

I didn't know about the indentation. Will watch out not to use tabs :D. About the double quotes: I tend to be a bit inconsistent with that. I usually don't even notice :see_no_evil:.

I'll have to rethink the sign in/up buttons anyways, I think it looks weird having two separate buttons with nearly identical labels. Will have to see how other sites solve the problem. 
For the own moves, I was actually thinking of making a site "Your stuff" (or something like that) where you can see all your submissions.

**Comment by davidpdrsn** [comment]
:+1:

**Pull request merged**
