### PR TITLE
Style index pages

### PR DESCRIPTION
**Pull request by corroded**
Sorry this is a large PR! Some notes, I first used http://rscss.io/ as my basis for the CSS, but upon reviewing the guidelines, switched to your suggested guidelines. 

Next, I usually work on a mobile first experience so that's what I focused on. @bendobos you might need to polish the desktop view more since I think it's still barren. I have hidden some info but if you can suggest a look for it I am willing to help out more on this aspect.

@davidpdrsn I tried copying your MoveWithUser class and did a VideoWithUser class. Took some liberties in adding some decorator info so let me know your thoughts on this. Lastly, I made some minor refactoring with the tests. Hope you don't mind my RSpec syntax, but if you feel strongly about using a different approach (I think this is the recommended Rspec 3 way?) then I can fix it up for you.

Oh and if you want me to squash commits, just let me know

Some screen shots (mobile/desktop/ipad views for moves/videos. As you can see, desktop view seems lacking. Maybe I should limit the width of the whole thing?

screen shot 2016-07-27 at 1 45 28 am
screen shot 2016-07-27 at 1 45 20 am
screen shot 2016-07-27 at 1 45 13 am
screen shot 2016-07-27 at 1 45 05 am
screen shot 2016-07-27 at 1 44 56 am
screen shot 2016-07-27 at 1 44 48 am

### CODE REVIEW

**Comment by davidpdrsn** [comment]
I am on vacation until august 6th. I will review everything when I'm back 😄

**Comment by corroded** [comment]
i envy you haha! No worries! I can still do some tweaks then :)

**Comment by bendobos** [comment]
Sorry that it took a while but I just had the time to check out your PR and it looks quite good! Some remarks:
- I will clean up the typography to be a bit more consistent with the styleguide that doesn't exist yet (:D)
- The filter options need some styling, I will see what I can come up with.
- It looks a bit basic right now. I'll see how I can add some pop.

Pretty good work until this point in my opinion. I'd say we merge this and I'll add the rest of the styling in another PR. 
I'm on my way to Munich for work right now but I might have the chance to get some things done in the evening.

**Comment by corroded** [comment]
Thanks man!

Yeah, I'm bad with typography but if we have a styleguide, should be pretty easy to fix up!

And yeah basically still need some styling for the filters and the yeah everythings a bit basic since I'm unsure what we should be adding. I think if we can make a styleguide, other people can help out with coding the other pages pretty quick.

**Pull request closed without merging**
