### PR TITLE
Styled Feed

### PR DESCRIPTION
**Pull request by bendobos**
- The feed is now styled
- All thumbnails have a placeholder for now
- There are some animations in place to let the activities (unobstrusively) fade in as you scroll
- There's a special view for new users when their feed is empty. I tried to make it very personal because I love websites that do this but let me know if you don't like it or if you'd like to write something different.
- I fixed some weird behavior with the footer
- Looks fine in the latest versions of Chrome, Safari and Firefox

For now, it is ready to go!

### CODE REVIEW

**Comment by bendobos** [comment]
There are quite a few tests failing but I can't quite figure out why. There seems to be a problem with filling in form fields, no matter if you select them by name, label or id...

Edit: This is pretty weird. It doesn't find most elements, like for example the approve videos link. It can't even be found if I add an id to the link and tell the test to look for that.

**Comment by davidpdrsn** [comment]
I believe I have fixed the failing tests now.

I dunno how but you had somehow managed to rename "config/environments" to "config/rails". That broke a whole bunch of things. Renaming the folder back fixed all the errors.

I rebased master on top of this branch and force pushed so dunno how your experience will be when pulling. Maybe you'll have to delete your branch and re-add it. Force pushing is usually evil but I really wanted [this](https://github.com/davidpdrsn/CardistryIO/pull/146) since I was gonna run lots of tests.

And by the way the feed looks fucking great! Awesome work! 💃 

I'll go a head and merge this right away.

**Comment by lpalmes** [comment]
I just pulled from master and just wanted to say the feed looks sweet, really nice work @bendobos !

**Comment by bendobos** [comment]
Thank you guys!

**Pull request merged**
