### PR TITLE
Setup environment variables during bootstrap

### PR DESCRIPTION
**Pull request by davidpdrsn**
@lpalmes @corroded this should fix the issues you've been having. Please give it a try and let me know if it works for you. Just run `script/bootstrap && script/server`.

### CODE REVIEW

**Comment by lpalmes** [comment]
Testing it right now in a clean digital ocean droplet, there is too much to download for my lousy connection. I let you know how it goes

**Comment by lpalmes** [comment]
Well, same old `RAILS_REDIS_1_PORT` buggin us down, i already added networking, so that should be fixed, @davidpdrsn shall i submit a pull request with the improvements?

**Comment by davidpdrsn** [comment]
@lpalmes e9cbfa9 should have fixed it. Let me know if it works

**Comment by lpalmes** [comment]
@davidpdrsn that's working smoothly, it seems good to merge
Thanks!

**Pull request merged**
