### PR TITLE
Form & add-pages styling

### PR DESCRIPTION
**Pull request by bendobos**
- I finally came up with a form styling that I am happy with and applied it to all of them
- The add move and add video pages are styled. I am not completely happy with it but since the whole upload system is subject to change, this is good enough for now. 
- I changed the "Sign up" and "Sign in" buttons to say "Sign up" and "Log in". Makes it quicker to scan the site for the button you need.

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Looks great! Would you also wanna look at styling of errors? Like when you submit a totally empty form.

**Comment by bendobos** [comment]
Shit, I forgot about that! Will get on that right away.

**Comment by davidpdrsn** [comment]
Looks good to me. Wanna rebase with master, squash and merge?

**Comment by bendobos** [comment]
This is now merged into master.

**Pull request closed without merging**
